import time
def time1():
    time.sleep(1.2)

print("☎ :: Welcome to KITT. ::")
a = input("Please enter your username. ")
print("☎ :: Running logon credentials for '" + a + "'... ::")
time1()
print("☎ :: Waiting...")
time1()
print("☎ :: Waiting...")
time.sleep(0.8)
print("☎ :: Waiting...")
time.sleep(0.8)
print("☎ :: Access GRANTED. Welcome, " + a + ". ::")
time.sleep(2)
print("☎ :: Your personal details are out-of-date, and need to be updated. ::")
time.sleep(1)
b = input("☎ :: How old are you? :: ")
print("☎ :: " + b + " - Confirmed. Re-added to database.")
time.sleep(1)
c = input("☎ :: Who is your favourite musician? :: ")
print("☎ :: " + c + ". " + "Favourite musician added to database.")
time.sleep(1)
d = input("☎ :: Please enter an alternative musician or band. :: ")
print("☎ :: " + d + ". Confirmed. " + d + " added to " + c + ".")
time.sleep(3)
e = input("☎ :: As part of my software improvement upgrade, KITT would like to tell a joke. Yes/No? :: ")
if e == "Yes":
    print("☎ :: How do robots eat salsa? With micro-chips! Ha-ha-ha! :: ")
if e == "No":
    print("☎ :: Acknowledged. :: ")

print("☎ :: Logging off... :: ")
time.sleep(2)
print("☎ :: Waiting... ::")
time.sleep(1.2)
print("☎ :: Waiting... ::")
time.sleep(1.2)
print("☎ :: Thank you for using KITT, " + a + ". ::")
time.sleep(5)
